### ISSUE TITLE
NullPointerException on orientation change, if control does not have android:id="@+id/ attribute

### ISSUE THREAD

**Issue by JonathanWillis** [JakeWharton/ViewPagerIndicator#100]
I've come across an unusual error which I "think" I have traced down to the ViewPageIndicator control. If the controls in the layout used for the Fragments (Views) do not have andorid:id="+@id/" attributes you get a null pointer exception when the activity is recreated, when the orientation changes from portrait to landscape.

I have a project using the ViewPageIndicator, using Titles.

I have the following classes
HomeFragment, HistoryFragment, HomeFragmentAdapter and HomeActivity.

Basically its an Activity with the ViewPagerIndicator, which contains just two views, Home and History.
The Layout for this Activity is below.

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical" >

```
<com.viewpagerindicator.TitlePageIndicator
    android:id="@+id/indicator"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:padding="10dip" />

<android.support.v4.view.ViewPager
    android:id="@+id/pager"
    android:layout_width="fill_parent"
    android:layout_height="0dp"
    android:layout_weight="1" />
```

</LinearLayout>

For this example, the Home and History fragements have the same code. They both just define the onCreateView method.

@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.historytab, container, false);
        return view;
    }

The layout for the history tab is as follows.

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

<TextView 
    android:id="@+id/txttest"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:text="History list!!!!"/>

</LinearLayout>

Using this works ok, but if the layout is missing the line (android:id="@+id/txttest") a nullpointerexception is raised when the phone changes from portrait to landscape. The stacktrace from LogCat is below

at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1576)
at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1617)
at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:481)
at android.app.Activity.performSaveInstanceState(Activity.java:1113)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1185)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3325)
at android.app.ActivityThread.access$700(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1151)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)

Its worth noting that if the layout for HomeFragment contains the android:id attribute, and layout for HistoryFragment does not. The exception is only raised when the rotation occurs if the HomeFragment is the current view on the screen.

**Comment by JakeWharton** [comment]
ViewPagerIndicator simply listens to events that come from the `ViewPager` instance its bound to. Any bugs or requirements of it are imposed by Google as it's their library and should be documented on http://d.android.com. If they aren't you're welcome to file a bug on their issue tracker at http://b.android.com

**Comment by JonathanWillis** [comment]
Thanks Jake, I'll search through the google libraries.
