### ISSUE TITLE
TitlePageIndicator.onTouchEvent() can throw

### ISSUE THREAD

**Issue by larham** [JakeWharton/ViewPagerIndicator#132]
from android.version: 2.3.5
brand/model: tmobile/HTC Glacier

using support-v4 r10

Throwable occurred: java.lang.NullPointerException
    at android.support.v4.app.Fragment.setUserVisibleHint(SourceFile:750)
    at android.support.v4.app.FragmentPagerAdapter.setPrimaryItem(SourceFile:130)
    at android.support.v4.view.ViewPager.populate(SourceFile:893)
    at android.support.v4.view.ViewPager.setCurrentItemInternal(SourceFile:469)
    at android.support.v4.view.ViewPager.setCurrentItemInternal(SourceFile:441)
    at android.support.v4.view.ViewPager.setCurrentItem(SourceFile:422)
    at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(SourceFile:531)
    at android.view.View.dispatchTouchEvent(View.java:3933)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
    at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:1236)
    at android.view.ViewRoot.dispatchDetachedFromWindow(ViewRoot.java:1868)
    at android.view.ViewRoot.doDie(ViewRoot.java:2977)
    at android.view.ViewRoot.die(ViewRoot.java:2947)
    at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:263)
    at android.view.Window$LocalWindowManager.removeViewImmediate(Window.java:445)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3268)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3373)
    at android.app.ActivityThread.access$1600(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1058)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:150)
    at android.app.ActivityThread.main(ActivityThread.java:4389)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Dupe #108.

**Comment by larham** [comment]
Thanks, I searched issues for the lowest part of the stack trace, finding none, but should have re-searched after I figured out what an appropriate title/fix would be.

**Comment by JakeWharton** [comment]
No problem. Release should be within a week.
