### ISSUE TITLE
Exception in graph. layout editor when using TabPageIndicator width=fill_parent

### ISSUE THREAD

**Issue by djusv** [JakeWharton/ViewPagerIndicator#155]
Just started using the ViewPageIndicator library.
I downloaded and compiled the project without any problems, on the first run.

Now i'm looking to res\layout\simple_tabs.xml in the graphical layout i receive this error:

``` java
Exception raised during rendering: ViewPager has not been bound.
Exception details are logged in Window > Show View > Error Log
java.lang.IllegalStateException: ViewPager has not been bound.
    at com.viewpagerindicator.TabPageIndicator.setCurrentItem(TabPageIndicator.java:240)
    at com.viewpagerindicator.TabPageIndicator.onMeasure(TabPageIndicator.java:116)
    at android.view.View.measure(View.java:15172)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
    at android.view.View.measure(View.java:15172)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:15172)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
    at android.view.View.measure(View.java:15172)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
    at android.view.View.measure(View.java:15172)
```

the xml is not modified:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">

    <com.viewpagerindicator.TabPageIndicator
        android:id="@+id/indicator"
        android:layout_height="wrap_content"
        android:layout_width="fill_parent"
        />
    <android.support.v4.view.ViewPager
        android:id="@+id/pager"
        android:layout_width="fill_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        />

</LinearLayout>
```

``` java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_consultation_overview);

        mAdapter = new PageAdapter(getSupportFragmentManager());

        mPager = (ViewPager) findViewById(R.id.pager);
        mPager.setAdapter(mAdapter);

        mIndicator = (TabPageIndicator) findViewById(R.id.indicator);
        mIndicator.setViewPager(mPager);
```

i was using the last stable version of ADT and the Android SDK Tools & Platform-tools,
now i'm on the preview channel with the same results. 

The code still runs fine after building but the graphical layout it broken, is there a way to fix this?

**Comment by Diederikjh** [comment]
I have the same problem with my preview layout in Eclipse.  In the activity's onCreate() I first set the adapter on the viewpager (By calling mViewPager.setAdapter(mAdapter)) and then setting the view pager on the indicator by calling mTabPageIndicator.setViewPager(mViewPager). 

However, Eclipse still complains about the ViewPager not being bound.  When I view the activity's XML file in Eclipse's preview view, I also set the correct activity for context.  I hoped that eclipse will then figure out what onCreate to call.  

Like I said this doesn't work in Eclipse preview mode, but runs fine when I deploy it to a tablet.

I am using eclipse Juno with ADT version 21 and version 2.3.1 of ViewPagerIndicator.

**Comment by yincrash** [comment]
For this to work, the class would need a dummy pager to use when using the graphical editor. You can either add one in your own copy of the library, or submit a patch for having one added. You would use View#isInEditMode() to make sure that only the graphical editor is using the dummy pager.

**Comment by kashban** [comment]
It's not only in the Eclipse preview but also crashes in my App on API level 19. API level 21 works, but without theming. My guess is that onMeasure() is called before my Activity has the chance to actually set the ViewPager. I have to load my configuration first, so the viewpager is set later in the starting process, not directly in onCreate().

```
Process: de.kashban.android.picturecalendar, PID: 28484
java.lang.IllegalStateException: ViewPager has not been bound.
        at com.viewpagerindicator.TabPageIndicator.setCurrentItem(TabPageIndicator.java:240)
        at com.viewpagerindicator.TabPageIndicator.onMeasure(TabPageIndicator.java:116)
        at android.view.View.measure(View.java:17387)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:17387)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
        at android.view.View.measure(View.java:17387)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:17387)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:17387)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:17387)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:17387)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5352)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2533)
        at android.view.View.measure(View.java:17387)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2213)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1352)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1549)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1236)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6471)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:573)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5356)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by vsopilko** [comment]
```
@Override
public void setCurrentItem(int item) {
    if (isInEditMode())
        return;
```

...............

**Comment by HungTDO** [comment]
Have everybody fixed it?
