### ISSUE TITLE
Example crash during rotation if we do not supply a value in bundle

### ISSUE THREAD

**Issue by yccheok** [JakeWharton/ViewPagerIndicator#210]
First, thanks for such a great library! It makes Android developer life easier :)

If I run the example by doing

Circle -> Default -> [Rotate the phone]

Everything works fine.

However, if I try to make modification on ViewPager's page, then perform the same actions again, it crashes.

https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/sample/src/com/viewpagerindicator/sample/TestFragment.java

```
@Override
public void onSaveInstanceState(Bundle outState) {
    super.onSaveInstanceState(outState);
    // If I comment the following line, 
    // the example will crash when I rotate the phone.
    //outState.putString(KEY_CONTENT, mContent);
}
```

Here's the error log.

```
 FATAL EXCEPTION: main
 java.lang.NullPointerException
    at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1576)
    at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1617)
    at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:481)
    at android.app.Activity.performSaveInstanceState(Activity.java:1137)
    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1215)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3486)
    at android.app.ActivityThread.access$700(ActivityThread.java:130)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4745)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

May I know why I need to supply at least 1 value in bundle in order to prevent it crashes? Is this a bug?

**Comment by yccheok** [comment]
Sorry. Appear to be support library bug itself.

https://code.google.com/p/android/issues/detail?id=19211

https://code.google.com/p/android/issues/detail?id=19917
