### ISSUE TITLE
Sample application throws an exception on exit

### ISSUE THREAD

**Issue by ai212983** [JakeWharton/ViewPagerIndicator#23]
If  any view is selected (Default, for example), application crashes on exit (like pressing home button). Here's the log:

10-27 16:08:20.675: ERROR/AndroidRuntime(1398): FATAL EXCEPTION: main
        java.lang.NoClassDefFoundError: [Landroid.support.v4.app.FragmentState;
        at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1537)
        at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:888)
        at android.app.Activity.performSaveInstanceState(Activity.java:1037)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1181)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2336)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2311)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2291)
        at android.app.ActivityThread.access$1700(ActivityThread.java:117)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3683)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by ai212983** [comment]
Weird. Everything is fine after reboot and re-installing. Will reopen issue if find a sure way to reproduce.
