### ISSUE TITLE
NotFoundException while inflating ViewPagerIndicator on android 4.4.2

### ISSUE THREAD

**Issue by 4nd3250n** [JakeWharton/ViewPagerIndicator#295]
ViewPagerIndicator works OK (tested) on 2.3.5, 2.3.6, 4.1.1. but not on 4.2.2.
I get this exception:

```
05-12 05:46:46.990: E/AndroidRuntime(1415): Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.viewpagerindicator.TabPageIndicator
05-12 05:46:46.990: E/AndroidRuntime(1415):     at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:305)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:509)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:359)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:647)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:465)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:415)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at android.support.v4.app._HoloActivity.requestDecorView(_HoloActivity.java:381)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at android.support.v4.app._HoloActivity.setContentView(_HoloActivity.java:414)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at com.itevo.nakupnik.ActivityFavorites.onCreate(ActivityFavorites.java:94)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at android.app.Activity.performCreate(Activity.java:5231)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
05-12 05:46:46.990: E/AndroidRuntime(1415):     ... 11 more
05-12 05:46:46.990: E/AndroidRuntime(1415): Caused by: java.lang.reflect.InvocationTargetException
05-12 05:46:46.990: E/AndroidRuntime(1415):     at java.lang.reflect.Constructor.constructNative(Native Method)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:281)
05-12 05:46:46.990: E/AndroidRuntime(1415):     ... 22 more
05-12 05:46:46.990: E/AndroidRuntime(1415): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01001c a=2}
05-12 05:46:46.990: E/AndroidRuntime(1415):     at android.content.res.Resources.loadDrawable(Resources.java:2068)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at com.viewpagerindicator.IcsLinearLayout.<init>(IcsLinearLayout.java:38)
05-12 05:46:46.990: E/AndroidRuntime(1415):     at com.viewpagerindicator.TabPageIndicator.<init>(TabPageIndicator.java:85)
05-12 05:46:46.990: E/AndroidRuntime(1415):     ... 25 more
05-12 05:46:51.380: I/Process(1415): Sending signal. PID: 1415 SIG: 9
```

**Comment by cycorax12** [comment]
You got any solution

**Comment by 4nd3250n** [comment]
Yes, I solved that. It was not problem with PageViewerIndicator directly. I was using theming based on API versions di i used folder modifiers and somehow one attribute got through undefined.
The key is to check this:
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01001c a=2}
For info: TypedArray contains TypeValues which describe style attributes, values and references IICR.
So the resource with Id 0x7f01001c was invalid.
If you have similar problem then check if one of your resources is not ok.
