### ISSUE TITLE
Getting crash reports saying "NoSuchMethod for isFakeDragging"

### ISSUE THREAD

**Issue by leowhiterussian** [JakeWharton/ViewPagerIndicator#37]
java.lang.NoSuchMethodError: android.support.v4.view.ViewPager.isFakeDragging
at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(TitlePageIndicator.java:480)
at android.view.View.dispatchTouchEvent(View.java:3932)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1015)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1784)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1157)
at android.app.Activity.dispatchTouchEvent(Activity.java:2228)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1759)
at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2340)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1980)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:4293)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
at dalvik.system.NativeStart.main(Native Method)

Is there a minimum API version that may be causing this?

**Comment by JakeWharton** [comment]
You have to be using the r4 or r5 compat library. The isFakeDragging method
was not present in the earlier revisions. Check your SDK Manager for
updates.

---

Jake Wharton
http://about.me/jakewharton

On Thu, Dec 15, 2011 at 3:04 PM, Leo Liberman <
reply@reply.github.com

**Comment by leowhiterussian** [comment]
I am using android-support-v4.jar, is that what you are referring to? I don't have any updates in sdk manager

**Comment by JakeWharton** [comment]
Yes but there are different revisions to the v4 compat library. Revision 4
added that method to the ViewPager class. If it is not present then you are
using revision 3.

http://developer.android.com/sdk/compatibility-library.html

You can use the one in the project's libs/ folder to ensure you have the
right version.

---

Jake Wharton
http://about.me/jakewharton

On Thu, Dec 15, 2011 at 3:26 PM, Leo Liberman <
reply@reply.github.com

**Comment by leowhiterussian** [comment]
Ah ic, ok thanks Jake!
