### ISSUE TITLE
Proguard fails because of warning for unresolved reference to ceil() in FloatMath

### ISSUE THREAD

**Issue by AntonioCappiello** [JakeWharton/ViewPagerIndicator#384]
Whenever I try to release an app with this library, my build server stop because proguard detects an unresolved reference to 'ceil()' in FloatMath with the following log message:

```
 :app:proguardProdRelease 
 Warning: com.viewpagerindicator.LinePageIndicator: can't find referenced method 'float ceil(float)' in library class android.util.FloatMath
 Warning: there were 1 unresolved references to library class members.
          You probably need to update the library versions.
          (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
 Exception while processing task 
 java.io.IOException: Please correct the above warnings first.
    at proguard.Initializer.execute(Initializer.java:473)
    at proguard.ProGuard.initialize(ProGuard.java:233)
    at proguard.ProGuard.execute(ProGuard.java:98)
    at proguard.gradle.ProGuardTask.proguard(ProGuardTask.java:1074)
    at com.android.build.gradle.tasks.AndroidProGuardTask.doMinification(AndroidProGuardTask.java:139)
    at com.android.build.gradle.tasks.AndroidProGuardTask$1.run(AndroidProGuardTask.java:115)
    at com.android.builder.tasks.Job.runTask(Job.java:48)
    at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
    at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:227)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Shirane85** [comment]
Hi, I can't upgrade the support library because of this issue. Please fix. Thanks!

**Comment by danielgomezrico** [comment]
@AntonioCappiello @Shirane85 use https://github.com/avianey/Android-ViewPagerIndicator with 

```
  compile 'fr.avianey.com.viewpagerindicator:library:2.4.1.1@aar'
```
