### ISSUE TITLE
Properly check if fakedrag is allowed before dragging

### ISSUE THREAD

**Issue by SimonVT** [JakeWharton/ViewPagerIndicator#80]
https://github.com/JakeWharton/Android-ViewPagerIndicator/blob/master/library/src/com/viewpagerindicator/TitlePageIndicator.java#L496

Replace:

``` java
if (!mViewPager.isFakeDragging()) {
    mViewPager.beginFakeDrag();
}

mLastMotionX = x;

mViewPager.fakeDragBy(deltaX);
```

With:

``` java
mLastMotionX = x;
if (mViewPager.isFakeDragging() || mViewPager.beginFakeDrag()) mViewPager.fakeDragBy(deltaX);
```

**Comment by JakeWharton** [comment]
Doesn't work. FC every time.

```
E/AndroidRuntime(16980): java.lang.IllegalStateException: No fake drag in progress. Call beginFakeDrag first.
E/AndroidRuntime(16980):    at android.support.v4.view.ViewPager.fakeDragBy(ViewPager.java:1708)
E/AndroidRuntime(16980):    at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(TitlePageIndicator.java:511)
```

**Comment by JakeWharton** [comment]
Nevermind. Merged to `dev`.

**Comment by kevinsawicki** [comment]
Has this fix been released yet?

**Comment by SimonVT** [comment]
yes
